'use client';
import {useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {MoviePlayer,PlayerHandle} from './movie-player';
import {normalize,validateSubmission} from '../lib/validation.mjs';
type Movie={id:string;category:string;problem:string;title:string;driveFileId:string;resourceKey:string;thumbnailKey:string;durationSeconds:number|null;playCount?:number};
type View={screen:'list'|'watch'|'form'|'complete';movieId?:string;from?:string};
type Submission={submissionId:string;movieId:string;comment:string};
const thumbs:Record<string,string>={mobility:'/assets/thumb-mobility.jpg',family:'/assets/thumb-family.jpg'};
function Guide({pose='popcorn'}:{pose?:string}) {return pose==='popcorn'?<span className="guide popcorn"><img src="/assets/anno-popcorn-source.png" alt="ポップコーンを食べる案内役"/></span>:<span className={'guide '+pose}><img src={'/assets/anno_'+pose+'.png'} alt={pose==='filming'?'カメラで撮影する案内役':'台本を読む案内役'}/></span>}
function Thumb({movie}:{movie:Movie}) {const [failed,setFailed]=useState(false);return thumbs[movie.thumbnailKey]&&!failed?<img className="thumb" src={thumbs[movie.thumbnailKey]} alt="" onError={()=>setFailed(true)}/>:<span className="thumb fallback">{movie.title}</span>}
export default function Cinema(){
 const [view,setView]=useState<View>({screen:'list'}),[movies,setMovies]=useState<Movie[]>([]),[mode,setMode]=useState(''),[environment,setEnvironment]=useState(''),[loading,setLoading]=useState(true),[catalogError,setCatalogError]=useState('');
 const [selected,setSelected]=useState(''),[drafts,setDrafts]=useState<Record<string,string>>({}),[error,setError]=useState(''),[pending,setPending]=useState(false),[unknown,setUnknown]=useState(false),[receipt,setReceipt]=useState<(Submission&{preview:boolean})|null>(null);
 const requestRef=useRef<Submission|null>(null),busy=useRef(false),heading=useRef<HTMLHeadingElement>(null),formRef=useRef<HTMLFormElement>(null),loadingRef=useRef(false);
 const comment=drafts[selected]||'', movie=movies.find(m=>m.id===view.movieId);
 const playerRef=useRef<PlayerHandle>(null);
 async function recordPlay(movieId:string){const playId=crypto.randomUUID();for(let attempt=0;attempt<2;attempt++){try{const res=await fetch('/api/plays',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({movieId,playId}),signal:AbortSignal.timeout(20000)});const data=await res.json();if(res.ok&&data.ok&&data.movieId===movieId&&Number.isInteger(data.playCount)){setMovies(previous=>previous.map(m=>m.id===movieId?{...m,playCount:Math.max(m.playCount||0,data.playCount)}:m));return}if(res.status<500)return;}catch{}}}
 function watch(id:string){if(busy.current)return;flushSync(()=>go({screen:'watch',movieId:id}));playerRef.current?.play();}
 async function load(){if(loadingRef.current)return;loadingRef.current=true;setLoading(true);setCatalogError('');try{const res=await fetch('/api/movies',{cache:'no-store'}),data=await res.json();if(!res.ok||!data.ok)throw Error();setMovies(data.movies);setMode(data.mode);setEnvironment(data.environment||'')}catch{setCatalogError('作品を読み込めませんでした。')}finally{setLoading(false);loadingRef.current=false}}
 useEffect(()=>{load();const sync=()=>{const hash=location.hash.slice(1).split('/');const s=hash[0];setView(s==='watch'?{screen:'watch',movieId:hash[1]}:s==='form'?{screen:'form',from:history.state?.from,movieId:hash[1]}:{screen:'list'});if(s==='form')setSelected(hash[1]||'')};sync();window.addEventListener('popstate',sync);return()=>window.removeEventListener('popstate',sync)},[]);
 useEffect(()=>{heading.current?.focus();window.scrollTo(0,0)},[view]);
 function go(next:View){if(busy.current)return;history.pushState({from:next.from},'',next.screen==='list'?'#list':`#${next.screen}/${next.movieId||''}`);setView(next);setError('');if(next.screen==='form'&&!unknown)setSelected(next.movieId||'')}
 function openForm(id?:string){go({screen:'form',movieId:unknown?requestRef.current?.movieId:id,from:id?'watch':'list'})}
 function back(){go(view.from==='watch'?{screen:'watch',movieId:view.movieId}:{screen:'list'})}
 function edit(value:string){setDrafts(d=>({...d,[selected]:value}));requestRef.current=null;setError('')}
 function check(){const candidate={submissionId:crypto.randomUUID(),movieId:selected,comment};const reason=validateSubmission(candidate);if(reason){setError(reason);return null}if(!movies.some(m=>m.id===selected)){setError('見た作品を選んでください。');return null}return {...candidate,comment:normalize(comment)}}
 function preview(){const candidate=check();if(!candidate)return;setReceipt({...candidate,preview:true});go({screen:'complete',movieId:selected})}
 async function submit(e:React.FormEvent){e.preventDefault();if(busy.current)return;const candidate=requestRef.current||check();if(!candidate)return;requestRef.current=candidate;busy.current=true;setPending(true);setError('');try{
  const res=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...candidate,website:new FormData(formRef.current!).get('website')}),signal:AbortSignal.timeout(20000)});const data=await res.json();
  if(data.ok&&data.submissionId===candidate.submissionId&&['created','already_recorded'].includes(data.status)) {setReceipt({...candidate,preview:false});setDrafts(d=>({...d,[candidate.movieId]:''}));requestRef.current=null;setUnknown(false);busy.current=false;go({screen:'complete',movieId:candidate.movieId})}
  else {const uncertain=res.status>=500||data.ok===true;setUnknown(uncertain);setError(data.message||'保存結果を確認できません。同じ内容で再確認してください。');if(!uncertain&&data.code!=='CONFLICT')requestRef.current=null;}
 }catch{setUnknown(true);setError('保存結果が不明です。入力を保持しています。「保存結果を再確認」を押してください。')}finally{busy.current=false;setPending(false)}}
 function invite(id?:string){return <button className="invite" onClick={()=>openForm(id)} disabled={!movies.length}><Guide/><span><strong>見た後に一言感想を<br/>聞かせてください</strong><small>感想フォームを開く →</small></span></button>}
 return <><header><button className="brand" onClick={()=>go({screen:'list'})}><span aria-hidden="true">▱</span> みらいシネマ</button><span className="english">MIRAI CINEMA</span></header>
 {mode==='demo'&&<aside className="demo">ローカル確認版 · 感想は送信・保存されません</aside>}{mode==='sheets'&&environment==='test'&&<aside className="demo">テスト版 · 感想はテスト用シートに保存されます</aside>}
 {view.screen==='list'&&<section className="hero"><div><p className="hand">みんなの想いが、<br/>あたらしい未来をつくる。</p><p className="hand subcopy">映像で、もっと、つながれる。</p></div></section>}
 <main className={view.screen==='form'||view.screen==='complete'?'narrow':''}>
 {view.screen==='list'&&<><h1 ref={heading} tabIndex={-1}>あなたに近いお悩みは？</h1><p className="intro">短い映画で、少し先の毎日を。</p>{loading?<p role="status">作品を読み込んでいます</p>:catalogError?<div role="alert"><p>{catalogError}</p><button className="primary" onClick={load}>再読込</button></div>:!movies.length?<p>ただいま作品を準備しています</p>:<div className="cards">{movies.map(m=><button key={m.id} className="card" onClick={()=>watch(m.id)}><Thumb movie={m}/><span className="card-copy"><small>{m.category}{m.durationSeconds?` · ${m.durationSeconds}秒`:''}</small><strong>{m.problem}</strong><small className="play-count">再生 {typeof m.playCount==='number'?m.playCount.toLocaleString():'—'}回</small><span className="card-action">▶ この未来を見てみる</span></span></button>)}</div>}{!loading&&!catalogError&&invite()}</>}
 {view.screen==='watch'&&<><button className="back" onClick={()=>go({screen:'list'})}>← お悩み一覧に戻る</button><h1 ref={heading} tabIndex={-1}>{movie?.problem||'作品を確認しています'}</h1>{movie?<><p className="intro">{movie.title}</p>{movie.driveFileId&&/^[\w-]+$/.test(movie.driveFileId)?<><MoviePlayer key={movie.id} movie={movie} ref={playerRef} onFirstPlay={()=>recordPlay(movie.id)}/><a className="drive-link" href={`https://drive.google.com/file/d/${encodeURIComponent(movie.driveFileId)}/view${movie.resourceKey?'?resourcekey='+encodeURIComponent(movie.resourceKey):''}`} target="_blank" rel="noopener noreferrer">Googleドライブで開く ↗</a></>:<div className="unconnected"><Thumb movie={movie}/><p>動画はまだ接続されていません。<br/><small>こちらは作品の静止画です。</small></p></div>}{invite(movie.id)}</>:<button className="primary" onClick={()=>go({screen:'list'})}>一覧へ戻る</button>}</>}
 {view.screen==='form'&&<><button className="back" onClick={back} disabled={pending}>← {view.from==='watch'?'動画':'お悩み一覧'}に戻る</button><div className="form-heading"><Guide pose="reading_script"/><h1 className="hand" ref={heading} tabIndex={-1}>あなたの一言、<br/>聞かせてください。</h1></div><form ref={formRef} onSubmit={submit} noValidate><label htmlFor="movie">見た作品</label><select id="movie" value={selected} disabled={pending||unknown} onChange={e=>{setSelected(e.target.value);requestRef.current=null;setError('')}}><option value="">見た作品を選んでください</option>{movies.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select><label htmlFor="comment">感想を一言</label><textarea id="comment" value={comment} disabled={pending||unknown} onChange={e=>edit(e.target.value)} placeholder="こんな未来になったら、うれしいな。" aria-describedby="hint count form-error" aria-invalid={!!error}/><div className="form-meta"><span id="hint">お名前は不要です。</span><span id="count">{Array.from(normalize(comment)).length} / 200</span></div><div className="trap" aria-hidden="true"><label>ウェブサイト<input name="website" tabIndex={-1} autoComplete="off"/></label></div>{error&&<p className="error" id="form-error" role="alert">{error}</p>}<button className="primary" type="submit" disabled={pending||!movies.length}>{pending?'送信しています…':unknown?'保存結果を再確認':mode==='demo'?'送信を試す（保存されません）':'感想を届ける'}</button>{mode==='demo'&&<button className="preview-link" type="button" onClick={preview} disabled={pending}>完了画面の見た目を確認（未送信） →</button>}<p className="privacy">{mode==='demo'?'デモの入力内容は、このタブ内だけで保持します。':'ご感想は運営メンバーが拝見します。'}</p></form></>}
 {view.screen==='complete'&&receipt&&<section className="thanks">{receipt.preview&&<p className="preview-notice" role="status">完了画面のプレビューです。<br/>この感想は送信・保存されていません。</p>}<Guide pose="filming"/><h1 className="hand" ref={heading} tabIndex={-1}>一言、ありがとう。</h1><p className="thanks-copy">あなたの想いを、<br/>次の物語のヒントに。</p><blockquote><small>{movies.find(m=>m.id===receipt.movieId)?.title}</small><p>{receipt.comment}</p></blockquote><button className="primary" onClick={()=>go({screen:'list'})}>ほかのお悩みも見てみる →</button></section>}
 </main><footer><p className="hand">今日のアイデアが、<br className="mobile-break"/>あしたのあたりまえに。</p><p>チームみらい　みらいシネマ</p><p>この作品は、AIで描いた未来の一案です。</p><small>案内役キャラクター原案：トリコさん</small></footer></>
}
